# Shared config mode preset configuration

config_version = 1

# Preset for real-time use, e.g. coupled with Sindri
[realtime]
    [realtime.main.general]
        output_path_client = "~/brokkr/realtime"

    [realtime.main.pipelines.telemetry]
        monitor_interval_s = 1

# Preset for real-time use with Sindri 0.2.x
[sindri02x]
    [sindri02x.main.pipelines.telemetry]
        monitor_interval_s = 10

# Preset for core and system testing without disturbing the production data
[test]
    [test.main.general]
        output_path_client = "~/brokkr/test"

    [test.main.pipelines.telemetry]
        monitor_interval_s = 5

    [test.main.steps.state_monitor]
        _enabled = false

    [test.main.steps.hamma_plot]
        _enabled = false

    [test.main.steps.hamma_plot_rsync]
        _enabled = false

    [test.main.steps.realtime_output_queue]
        _enabled = false

    [test.main.steps.realtime_input_queue]
        _enabled = false

    [test.main.pipelines.realtime]
        _enabled = false

    [test.main.pipelines.rsync_hamma_realtime]
        _enabled = false
